# Site Settings
baseurl: 		/
title: 			code 'n fold

name: 			code <i>'n</i> fold
description: 	Code and Origami – Software Engineering
url: 			"http://www.code-n-fold.com"

paginate: 		5
paginate_path: 	"blog/page:num"

twitter: 		code_n_fold
email: 			daniel.kummer@gmail.com

disqus: 		danielkummer
analytics: 		UA-66459836-1

copyright: 		Copyright 2015 Daniel Kummer.

# Build Settings
permalinks: 	pretty

#output settings
#permalink: '/:year/:month/:title'

gems:
  - jekyll-redirect-from

exclude: ['Gemfile', 'Gemfile.lock', 'Rakefile', 'README.md']
